
#ifndef __GAME_UTILS_H__
#define __GAME_UTILS_H__

#include "CCF_Utils.h"

namespace SlashSave
{
	enum
	{
		GAME_OBJECT_TAG_PLAYER = 0b00001111,
		GAME_OBJECT_TAG_BRUSH_DOT = 0b00000000,
		GAME_OBJECT_TAG_OBSTACLE = 0b00000001,
		GAME_OBJECT_TAG_UP_SPEED_PICKUP = 0b11110000,
		GAME_OBJECT_TAG_COIN_PICKUP = 0b11110001
	};

	enum
	{
		GAMEPLAY_LOCAL_Z_BACKGROUND,
		GAMEPLAY_LOCAL_Z_GAME_OBJECT,
		GAMEPLAY_LOCAL_Z_BRUSHES
	};

	bool IsInScreen(const CCF_Vec2& worldCoord);
}

#endif